when:
  - event: [push, pull_request]

steps:
  deps:
    image: elixir:1.18
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get

  compile:
    image: elixir:1.18
    commands:
      - mix local.hex --force
      - mix compile --warnings-as-errors

  test:
    image: elixir:1.18
    commands:
      - mix test

  format-check:
    image: elixir:1.18
    commands:
      - mix format --check-formatted
